---
- name: Configure git user name
  git_config:
    name: user.name
    value: "{{ git_user_name }}"
    scope: global
  become_user: "{{ user_name }}"

- name: Configure git user email
  git_config:
    name: user.email
    value: "{{ git_user_email }}"
    scope: global
  become_user: "{{ user_name }}"

- name: Configure git default branch to main
  git_config:
    name: init.defaultbranch
    value: main
    scope: global
  become_user: "{{ user_name }}"

- name: Configure git pull strategy to merge
  git_config:
    name: pull.rebase
    value: "false"
    scope: global
  become_user: "{{ user_name }}"